### ISSUE TITLE
same error

### ISSUE THREAD

**Issue by livcoding2** [tamton-aquib/bruttle#4] opened 2024-02-24 18:02 UTC
module 'pikepdf' has no attribute '_qpdf'

**Comment by tamton-aquib** [comment] 2024-02-24 18:07
Heyyo @livcoding2,
Which OS are you on? Can you provide the full error?

**Comment by livcoding2** [comment] 2024-02-24 18:41
Macos Monterey m1
it seems strange to me, that if I put only one line in the wordlist, it works.

`Bruteforcing:   0%|                                                        | 0/13232 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "/opt/homebrew/lib/python3.11/site-packages/bruttle/bruttle.py", line 17, in ettup
    with pikepdf.open(target, password=passwd) as pdfile:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/pikepdf/_methods.py", line 400, in open
    pdf = Pdf._open(
          ^^^^^^^^^^
pikepdf._core.PasswordError: laura.pdf: invalid password

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/homebrew/bin/bruttle", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/bruttle/bruttle.py", line 65, in main
    { ".zip": ettuz, "": ettuh, ".pdf": ettup }.get(extension, log)(target, lines)
  File "/opt/homebrew/lib/python3.11/site-packages/bruttle/bruttle.py", line 23, in ettup
    except pikepdf._qpdf.PasswordError:
           ^^^^^^^^^^^^^
AttributeError: module 'pikepdf' has no attribute '_qpdf'`

**Comment by livcoding2** [comment] 2024-02-24 18:43
look here with a wordlist that has only one entry.

liv@UNIX[±|main ?:5 ✗]:~/.../PDF/bruttle $ bruttle laura.pdf apache.txt
 Bruteforcing:   0%|                                                            | 0/1 [00:00<?, ?it/s]
---------------------------------------------
          Found Password: -->  laura
---------------------------------------------
liv@UNIX[±|main ?:5 ✗]:~/.../PDF/bruttle $

**Comment by tamton-aquib** [comment] 2024-02-24 18:51
Its the expected behaviour if its just one password since its not reaching the `except` block.
But the main issue is weird, I will check it tomorrow.

I am currently working on veldora (https://github.com/tamton-aquib/veldora) . It is much quicker than this tool (bruttle). It has multithreading and is written in rust. If you are in a hurry you could check it out until this issue gets resolved.

**Comment by tamton-aquib** [comment] 2024-02-25 09:08
Heyyo @livcoding2,

The issue should be fixed now and I have released the v1.0.0 version.
You could `pip uninstall bruttle` and then install it via `pip install bruttle` again to check.

**Comment by livcoding2** [comment] 2024-02-25 11:39
Yes, thanks, but is too slow. Thank you anyway for your time and work.
Veldora working but didnt find right password.

**Comment by tamton-aquib** [comment] 2024-02-25 13:52
Veldora worked fine for me with nearly 10 pdfs i tested with. Maybe an issue with the wordlist?

Anyway, feel free to close the issue if you feel its been resolved 😅 .

**Comment by tamton-aquib** [comment] 2024-02-28 15:46
Closing this issue for now.  Feel free to re-open if there is any more issues 👍🏻

**Closed as completed by tamton-aquib** 2024-02-28 15:46 UTC
